Add addImage test
mapbox/mapbox-gl-test-suite pull request #201
Opened 2017-01-06 22:56 UTC by bsudekum

Works along side with https://github.com/mapbox/mapbox-gl-native/pull/7610

/cc @jfirebaugh

2017-01-06 23:07 UTC, jfirebaugh requested changes

2017-01-06 23:07 UTC, jfirebaugh commented on render-tests/add-image/default/style.json
> +      "center": 0,
Remove the extraneous `center` and `zoom` properties.

2017-01-06 23:07 UTC, jfirebaugh commented on render-tests/add-image/default/style.json
> +          "wait"
This initial `wait` operation isn't necessary.

2017-01-06 23:07 UTC, jfirebaugh commented on render-tests/add-image/default/style.json
> +      "data": {
Simplify:

```
"data": {
  "type": "Point",
  "coordinates": [0, 0]
}
```

2017-01-06 23:07 UTC, jfirebaugh commented on render-tests/add-image/default/style.json
> +      "id": "background",
This background layer isn't necessary. It's fine to have a partially-transparent result.

2017-01-06 23:07 UTC, jfirebaugh commented
Move the test to `render-tests/runtime-styling/image-add/style.json`.

2017-01-06 23:38 UTC, bsudekum commented
@jfirebaugh fixed

2017-01-09 18:27 UTC, jfirebaugh approved these changes

2017-01-09 18:27 UTC, merged